version: '3.8'

services:
  spring-docker:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL:
      SPRING_DATASOURCE_USERNAME:
      SPRING_DATASOURCE_PASSWORD: